import Footer, { FOOTER_HEIGHT } from '@/components/common/Footer'
import Navbar, { NAVBAR_HEIGHT } from '@/components/common/Navbar'
import Sidebar, {
  COLLAPSE_SIDEBAR_WIDTH,
  EXPANDED_SIDEBAR_WIDTH,
  LAYOUT_TRANSITION,
} from '@/components/common/Sidebar'
import { useAppSelector } from '@/configs/redux/hooks'
import { selectConfig } from '@/stores/config/selector'
import { Box, styled } from '@mui/material'
import type { Metadata } from 'next'

const WrapContainer = styled('div')({
  position: 'relative',
  height: '100%',
  transition: LAYOUT_TRANSITION
})

const ContentContainer = styled('div')({
  width: '100%',
  paddingTop: `${NAVBAR_HEIGHT}px`,
  minHeight: `calc(100vh - ${FOOTER_HEIGHT}px)`,
  backgroundColor: 'blueviolet',
  boxSizing: 'border-box',
})

export const metadata: Metadata = {
  title: 'HR Attendance',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { isOpenedSidebar, isAttachedSidebar } = useAppSelector(selectConfig)
  return (
    <Box>
      <Sidebar />
      <WrapContainer
        sx={{
          marginLeft: `${
            (isOpenedSidebar && isAttachedSidebar) ? EXPANDED_SIDEBAR_WIDTH : COLLAPSE_SIDEBAR_WIDTH
          }px`,
          width: `calc(100% - ${
            (isOpenedSidebar && isAttachedSidebar) ? EXPANDED_SIDEBAR_WIDTH : COLLAPSE_SIDEBAR_WIDTH
          }px)`,
        }}
      >
        <Navbar />
        <ContentContainer>{children}</ContentContainer>
        <Footer />
      </WrapContainer>
    </Box>
  )
}
